### ISSUE TITLE
zbugowane chunki / grupowe teparki na spawnie

### ISSUE THREAD

**Issue by Larmel144hz** [Rollczi/SaveMc-Issues#18]
Poszedlem na grupowe tp z typkiem nie wczytalo jakby swiata wokol mnie tylko byl void slyszalem tylko jak mnie bije i umarlem
//
itki dla mnie sa niewazne chcialbym poprostu odzyskac pnkt i miec stare statystyki
//
staty przed smiercia
https://imgur.com/a/czmCRHH
//
ile dostalem na minus
https://imgur.com/a/26w010X
//
jak to wygladalo / ss jest z singleplayer
https://imgur.com/a/wVdvVn4
//
nick: Larmel144hz
//
prosze o szybka odpowiedz
//

**Comment by Rollczi** [comment]
Hej, nie odpowiadamy za problemy z łącznością, komputerem lub z renderem gry. Zgłoszenie zostało odrzucone.
