### ISSUE TITLE
Sprawa o nowe craftingi 

### ISSUE THREAD

**Issue by Larmel144hz** [Rollczi/SaveMc-Issues#19]
SandFarmer
![image](https://i.imgur.com/aVabmZz.png)
BoyFarmer
![image](https://user-images.githubusercontent.com/49173834/115579782-c8bd3700-a2c6-11eb-92e2-d2093a01379b.png)
KopaczFosy / sa tutaj 2 pomysly mozesz sobie wybrac 
![image](https://user-images.githubusercontent.com/49173834/115579855-da9eda00-a2c6-11eb-9029-4441c5b18590.png)
![image](https://user-images.githubusercontent.com/49173834/115579896-e38fab80-a2c6-11eb-9f4c-1ce874bd128f.png)

**Comment by Rollczi** [comment]
Zmieniono, w ostatecznej formie:
![image](https://user-images.githubusercontent.com/49173834/115600894-73405480-a2dd-11eb-8e41-27a489d5cd6a.png)
![image](https://user-images.githubusercontent.com/49173834/115600904-74718180-a2dd-11eb-9ec0-a2d89deda280.png)
![image](https://user-images.githubusercontent.com/49173834/115600908-750a1800-a2dd-11eb-8015-c2aaed0fb029.png)
