### ISSUE TITLE
Sprawa Uliminate coins

### ISSUE THREAD

**Issue by Larmel144hz** [Rollczi/SaveMc-Issues#20]
sprawa wyglada tak ze nie trafilem  w enderchesta i moneta znikla bo to fireball xD
prosze o zwrot 1 uliminate coinsa
i jeszcze zrobcie cos takiego zeby sie nie dalo strzelac fireballami 

nick:Larmel144hz

**Comment by 37delfin** [comment]
dowody ? :D

**Comment by Rollczi** [comment]
Przyjęte. (Zgłoszenie pierwszy raz takiego błędu traktuje jako dowód)
