### ISSUE TITLE
Problemy z zalogowaniem

### ISSUE THREAD

**Issue by TheXWiur** [Rollczi/SaveMc-Issues#23]
Przez ostatni dodatek do logowanie mianowicie konta premium jak mam konto kokos i prubuję wejść przez crystal luncher to nie mogę mimo to że zaregisterowałem się przez crystal luncher a jak konto kokos to konto nie założone na premium przezemnie.

**Comment by Rollczi** [comment]
Rozumiem, że konto Kokos nie jest twoje i używasz nie swojej premki (bez sesji premki)?

**Comment by Rollczi** [comment]
Rozwiązane, problem naprawiony.
