### ISSUE TITLE
Problemy z wbiciem na savemc.eu 

### ISSUE THREAD

**Issue by TheXWiur** [Rollczi/SaveMc-Issues#24]
Nie moge wbić z mojego nowego kompa na savemc.eu bo dostaję komunikat      
      Zostałeś wyrzucony!
Powód: Wygląda na to, że używasz VPN lub Proxy
       Przez: CONSOLE

**Comment by TheXWiur** [comment]
Misclickiem to zamkłem

**Comment by Rollczi** [comment]
Proszę wyłącz swojego VPN. Nie możemy pozwolić na zakrywanie adresów IP. Inaczej można by botować serwer.

**Comment by TheXWiur** [comment]
A jak mam VPN wyłączyć?

**Comment by Rollczi** [comment]
Może inaczej. Jakimś dziwnym trafem masz IP z Litwy które zostało zgłoszone jako VPN i jest dodane do blacklisty. VPN to usługa prywatna i nie wiem jak ją sobie włączasz i wyłączasz.
