### ISSUE TITLE
Prośba

### ISSUE THREAD

**Issue by McKapiQ** [Rollczi/SaveMc-Issues#5]
Mam prośbe czy mógł byś dodać ze mozna miec działke w neterze i endzie poniewaz sznajd3R rozwalił całe nasze przejscie i prawdopodobnie podal kordy naszego spawneru blaze i rozwalił wszystkie nasz portale w neterze

**Comment by Rollczi** [comment]
Spawnery powinny być publiczne.
Portal możesz ponownie wygenerować np jak masz na działce to `/dom 1` i wchodzisz do portalu.
Podaj kordy spawneru jeśli zostały rozwalone konstrukcje twierdzy to mogę je przywrócić rollbackiem z logblocka.
Nie możemy pozwolić na działki w netherze i endzie z paru powodów.
- Co jakiś czas restartujemy te światy i było by to bezsensu.
- W netherze i szczególnie w  endzie jest za mało miejsca.
- Można wtedy farmić na blaze, enderman i innych mobach bez żadnego wysiłku (PvE jest wyłączone na działkach)
- Portale do netherowe można blokować z 2 stron (2 światów)
- Wyjście do endu może zostać zablokowane
- Ludzie postawiają działki i nie można dojść do jakiegoś spawnera baze.
