### ISSUE TITLE
Problem z panelem działek.

### ISSUE THREAD

**Issue by Look-For-Me** [Rollczi/SaveMc-Issues#64]
Zgłaszam drobny problem z panelem działek, nie wiem czy ktoś się spotkał z tym problemem, czy też nie. Nie mniej jednak u mnie po wpisaniu komendy /panel <nr działki> nie ważne jaki właśnie ten numer działki wpiszę, to teleportuje mnie, poprzez kliknięcie ikony łóżka, zawsze na pierwszą stworzoną działkę, którą postawiłem. Lecz na górze normalnie jest napisane w którym panelu aktualnie się znajduję.

**Comment by Rollczi** [comment]
Okej, naprawione. Nowa kompilacja wejdzie później w nocy.
